import { AIR, isWater, isFlowing, waterLevel, flowingWater } from '../config/blocks.js';

/**
 * Water that runs.
 *
 * Requested directly: "would be nice to have flowing water, and if it is on a
 * higher block, it should flow down." Every river, lake and sea is still
 * water — sources (block 11) that never move. What this adds is what runs off
 * them once something opens a way: dig a channel from a river and it fills,
 * pour a bucket on a hilltop and it spills down the slope.
 *
 * One rule, asked of each cell in turn: how strong would water be here?
 *   - a source is a source (8), always;
 *   - water directly above means it's falling into this cell: 7;
 *   - otherwise the strongest neighbour beside it, less one — counting only
 *     neighbours resting on solid ground or still water. Water with air
 *     under it falls rather than spreading, and so does water on top of a
 *     falling column: without that, a waterfall filled in sideways at every
 *     height on the way down, into a wall of water.
 * A cell with no supply (0) is air. Because every cell reads its level off
 * its neighbours rather than being pushed, the same rule spreads water out,
 * pours it down, and dries up a spill when its source is taken away.
 *
 * Nothing runs until something changes: `touch` wakes the cells round an
 * edit, and `step` settles one ring outwards each call — so a spill visibly
 * advances a block at a time instead of appearing all at once. Only air and
 * flowing water are ever replaced, and chunks not yet made are left alone
 * rather than generated by looking.
 */

const DIRS = [[1, 0, 0], [-1, 0, 0], [0, 0, 1], [0, 0, -1], [0, 1, 0], [0, -1, 0]];
const SIDES = DIRS.slice(0, 4);

/** How many cells one step will settle, so a flood can't stall a frame. */
const PER_STEP = 600;

export class WaterFlow {
  constructor(world) {
    this.world = world;
    this.pending = new Map(); // key -> [x, y, z]
  }

  /** Wakes a cell and everything touching it. */
  touch(x, y, z) {
    this.wake(x, y, z);
    for (const [dx, dy, dz] of DIRS) this.wake(x + dx, y + dy, z + dz);
  }

  wake(x, y, z) {
    if (y < 0 || y >= this.world.height) return;
    this.pending.set(`${x},${y},${z}`, [x, y, z]);
  }

  get busy() {
    return this.pending.size > 0;
  }

  /**
   * Settles what's waiting, once — cells woken by these changes wait for
   * the next step. Returns how many blocks changed.
   */
  step() {
    if (!this.pending.size) return 0;
    const now = [...this.pending.values()].slice(0, PER_STEP);
    for (const [x, y, z] of now) this.pending.delete(`${x},${y},${z}`);
    let changed = 0;
    for (const [x, y, z] of now) {
      if (this.settle(x, y, z)) changed++;
    }
    return changed;
  }

  /** Brings one cell to the level its neighbours say it should be at. */
  settle(x, y, z) {
    if (!this.loaded(x, z)) return false;
    const id = this.world.getBlock(x, y, z);
    if (id !== AIR && !isFlowing(id)) return false;
    const want = this.supply(x, y, z);
    const next = want > 0 ? flowingWater(want) : AIR;
    if (next === id) return false;
    this.world.setBlock(x, y, z, next);
    for (const [dx, dy, dz] of DIRS) this.wake(x + dx, y + dy, z + dz);
    return true;
  }

  /** How strong water would be in this cell, from what's around it: 0..7. */
  supply(x, y, z) {
    if (y + 1 < this.world.height && isWater(this.block(x, y + 1, z))) return 7;
    let best = 0;
    for (const [dx, , dz] of SIDES) {
      const nx = x + dx, nz = z + dz;
      const level = waterLevel(this.block(nx, y, nz));
      if (level <= 1 || level - 1 <= best) continue;
      // Water falling — onto air, or down a column of running water — doesn't
      // feed its neighbours; only water resting on something does.
      const under = y > 0 ? this.block(nx, y - 1, nz) : -1;
      if (under === AIR || isFlowing(under)) continue;
      best = level - 1;
    }
    return best;
  }

  /** A block, or a wall for a chunk that isn't there — never generate one. */
  block(x, y, z) {
    return this.loaded(x, z) ? this.world.getBlock(x, y, z) : -1;
  }

  loaded(x, z) {
    return this.world.hasChunk(x >> 4, z >> 4);
  }
}
