// Achievement definitions. `check(ctx)` receives { stats, event } and returns
// true once the achievement should unlock. `stats` is the cumulative
// gamification snapshot (see gamification/GamificationEngine.js), `event` is
// the specific action that just happened (place/break/levelup/etc), or null
// for periodic re-checks.
export const ACHIEVEMENTS = [
  {
    id: 'first_steps',
    name: 'First Steps',
    description: 'Place your first block.',
    icon: '🧱',
    xpReward: 10,
    check: (ctx) => ctx.stats.totalBlocksPlaced >= 1,
  },
  {
    id: 'getting_started',
    name: 'Getting Started',
    description: 'Place 25 blocks.',
    icon: '🔨',
    xpReward: 25,
    check: (ctx) => ctx.stats.totalBlocksPlaced >= 25,
  },
  {
    id: 'builder',
    name: 'Builder',
    description: 'Place 100 blocks.',
    icon: '🏗️',
    xpReward: 50,
    check: (ctx) => ctx.stats.totalBlocksPlaced >= 100,
  },
  {
    id: 'architect',
    name: 'Architect',
    description: 'Place 500+ blocks in a single build session.',
    icon: '🏛️',
    xpReward: 150,
    check: (ctx) => ctx.stats.sessionBlocksPlaced >= 500,
  },
  {
    id: 'collector',
    name: 'Block Collector',
    description: 'Use every base block type at least once.',
    icon: '🎨',
    xpReward: 100,
    check: (ctx) => ctx.stats.distinctTypesPlacedEver.size >= 13,
  },
  {
    id: 'sky_high',
    name: 'Sky High',
    description: 'Place a block at height 40 or above.',
    icon: '🌤️',
    xpReward: 60,
    check: (ctx) => ctx.stats.maxHeightPlaced >= 40,
  },
  {
    id: 'underground',
    name: 'Into the Depths',
    description: 'Build underground, beneath the surface.',
    icon: '⛏️',
    xpReward: 60,
    check: (ctx) => ctx.stats.undergroundActions >= 1,
  },
  {
    id: 'bridge_builder',
    name: 'Bridge Builder',
    description: 'Build a 5+ block bridge over open air.',
    icon: '🌉',
    xpReward: 60,
    check: (ctx) => ctx.stats.bridgesBuilt >= 1,
  },
  {
    id: 'first_house',
    name: 'First House',
    description: 'Fully enclose a space with walls and a roof.',
    icon: '🏠',
    xpReward: 100,
    check: (ctx) => ctx.stats.enclosedSpacesFound >= 1,
  },
  {
    id: 'level_5',
    name: 'Leveling Up',
    description: 'Reach level 5.',
    icon: '⭐',
    xpReward: 0,
    check: (ctx) => ctx.stats.level >= 5,
  },
  {
    id: 'level_10',
    name: 'Seasoned Builder',
    description: 'Reach level 10.',
    icon: '🌟',
    xpReward: 0,
    check: (ctx) => ctx.stats.level >= 10,
  },
  {
    id: 'streak_3',
    name: 'Consistent',
    description: 'Build on 3 consecutive days.',
    icon: '🔥',
    xpReward: 40,
    check: (ctx) => ctx.stats.streakCount >= 3,
  },
  {
    id: 'streak_7',
    name: 'Dedicated',
    description: 'Build on 7 consecutive days.',
    icon: '🔥',
    xpReward: 100,
    check: (ctx) => ctx.stats.streakCount >= 7,
  },
  {
    id: 'streak_30',
    name: 'Unstoppable',
    description: 'Build on 30 consecutive days.',
    icon: '🔥',
    xpReward: 400,
    check: (ctx) => ctx.stats.streakCount >= 30,
  },
  {
    id: 'architect_draft',
    name: 'Draughtsman',
    description: 'Save your first building template.',
    icon: '\u{1F4D0}',
    xpReward: 60,
    check: (ctx) => ctx.stats.templatesSaved >= 1,
  },
  {
    id: 'template_library',
    name: 'Pattern Book',
    description: 'Save 5 different templates.',
    icon: '\u{1F4DA}',
    xpReward: 140,
    check: (ctx) => ctx.stats.templatesSaved >= 5,
  },
  {
    id: 'prefab_town',
    name: 'Prefab Town',
    description: 'Stamp your own templates 10 times.',
    icon: '\u{1F3D8}',
    xpReward: 160,
    check: (ctx) => ctx.stats.templatesPlaced >= 10,
  },
  {
    id: 'grand_design',
    name: 'Grand Design',
    description: 'Save a template of 400 blocks or more.',
    icon: '\u{1F3DB}',
    xpReward: 200,
    check: (ctx) => ctx.stats.largestTemplateBlocks >= 400,
  },
  {
    id: 'challenge_master',
    name: 'Challenge Master',
    description: 'Complete 5 daily challenges.',
    icon: '🏆',
    xpReward: 120,
    check: (ctx) => ctx.stats.challengesCompleted >= 5,
  },
];

export const ACHIEVEMENTS_BY_ID = new Map(ACHIEVEMENTS.map((a) => [a.id, a]));
